name: Workflow Versioning  # self version this workflow

on:
  push:
    branches:
      - main
      - releases/** # If you need to maintain an old major or minor version, branch it to (e.g.) releases/v1

jobs:
  versioning:
    name: Release

    permissions:
      contents: write
    uses: ./.github/workflows/action_versioning.yml